# Generated by Django 5.0.2 on 2024-03-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employee_dept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bonous',
            new_name='bonus',
        ),
    ]
